---
depends_on: null
kind: pipeline
type: kubernetes
name: build-devcenter

steps:
- name: publish-staging
  image: plugins/kaniko-ecr
  environment:
    NPM_AUTH:
      from_secret: NPM_AUTH
    NPM_EMAIL:
      from_secret: NPM_EMAIL
    STRAPI_URL:
      from_secret: STRAPI_URL_STAGING
  settings:
    create_repository: true
    registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
    repo: devrel/${DRONE_REPO_NAME}
    build_args:
      - NPM_AUTH
      - NPM_EMAIL
      - STRAPI_URL
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}
    - latest
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
    values_files: [ "environments/staging.yaml" ]
  when:
    event:
    - push

- name: publish-production
  image: plugins/kaniko-ecr
  environment:
    NPM_AUTH:
      from_secret: NPM_AUTH
    NPM_EMAIL:
      from_secret: NPM_EMAIL
    STRAPI_URL:
      from_secret: STRAPI_URL_PROD
  settings:
    create_repository: true
    registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
    repo: devrel/${DRONE_REPO_NAME}
    build_args:
      - NPM_AUTH
      - NPM_EMAIL
      - STRAPI_URL
    tags:
    - git-${DRONE_COMMIT_SHA:0:7}
    - latest
    access_key:
      from_secret: ecr_access_key
    secret_key:
      from_secret: ecr_secret_key
    values_files: [ "environments/prod.yaml" ]
  when:
    event:
    - push

- name: deploy-staging
  image: quay.io/mongodb/drone-helm:v3
  settings:
    chart: mongodb/web-app
    chart_version: 4.7.3
    add_repos: [mongodb=https://10gen.github.io/helm-charts]
    namespace: devrel
    release: devcenter-frontend
    values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=devcenter-frontend.devrel.staging.corp.mongodb.com
    api_server: https://api.staging.corp.mongodb.com
    kubernetes_token:
      from_secret: staging_kubernetes_token
    values_files: [ "environments/staging.yaml" ]
  when:
    event:
    - push

trigger:
  branch:
    - main
  event:
    - push

---
depends_on: null
kind: pipeline
type: kubernetes
name: deploy-devcenter-prod

steps:
- name: deploy-prod
  image: quay.io/mongodb/drone-helm:v3
  settings:
    chart: mongodb/web-app
    chart_version: 4.7.3
    add_repos: [mongodb=https://10gen.github.io/helm-charts]
    namespace: devrel
    release: devcenter-frontend
    values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=devcenter-frontend.devrel.prod.corp.mongodb.com
    api_server: https://api.prod.corp.mongodb.com
    kubernetes_token:
      from_secret: prod_kubernetes_token
    values_files: [ "environments/prod.yaml" ]

trigger:
  event:
    - promote
    - rollback
  target:
    - production