---
kind: pipeline
type: kubernetes
name: default

steps:
  # - name: tests
  #   image: #todo
  #   commands:
  #     - # run tests
  
  # - name: linting
  #   image: #todo
  #   commands:
  #     - # run tests

  - name: build
    image: node:14.17.0
    commands:
       - touch .env.local
       - echo STRAPI_URL=${STRAPI_URL} >> .env.local
       - echo NPM_AUTH=${NPM_AUTH} >> .env.local
       - echo NPM_EMAIL=${NPM_EMAIL} >> .env.local
       - yarn install
       - yarn run build
    environment:
      NPM_AUTH:
        from_secret: NPM_AUTH
      NPM_EMAIL:
        from_secret: NPM_EMAIL
      STRAPI_URL:
        from_secret: STRAPI_URL

  - name: s3-sync
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_S3_IAM_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_S3_IAM_SECRET_ACCESS_KEY
      AWS_BUCKET_NAME:
        from_secret: AWS_S3_URI
    commands:
      - aws s3 sync .next $AWS_BUCKET_NAME --region us-east-1
        # Example cache args for cache control, exclusion etc, --cache-control public,max-age=31536000,immutable --exclude "*.js.map"
    when:
      event:
        - push