version: 2
snapshot:
    widths:
        - 375
        - 1280
    minHeight: 1024
    percyCSS: ''
discovery:
    allowedHostnames: []
    disallowedHostnames: []
    networkIdleTimeout: 5000

upload:
    files: '**/*.{png,jpg,jpeg}'
    ignore: ''
    stripExtensions: false
