service:
  type: ClusterIP
  targetPort: 3000

env:
  ACCOUNT_PORTAL_URL: https://account-qa.mongodb.com
  APP_ENV: staging
  HOST_URL: devhub-1167-preview.devrel.staging.corp.mongodb.com
  NEXTAUTH_URL: https://devhub-1167-preview.devrel.staging.corp.mongodb.com/developer/api/auth/

envSecrets:
  DEVHUB_URL: devcenter-secrets
  NEXTAUTH_SECRET: devcenter-secrets
  NPM_EMAIL: devcenter-secrets
  NPM_AUTH: devcenter-secrets
  OKTA_ISSUER: devcenter-secrets
  OKTA_CLIENT_ID: devcenter-secrets
  OKTA_CLIENT_SECRET: devcenter-secrets
  PREVIEW_SECRET_KEY: devcenter-secrets
  PROMETHEUS_AUTH_USER: devcenter-secrets
  PROMETHEUS_AUTH_PASS: devcenter-secrets
  REALM_API_URL: devcenter-secrets
  REALM_SEARCH_URL: devcenter-secrets
  REVALIDATE_TOKEN: devcenter-secrets
  SENTRY_AUTH_TOKEN: devcenter-secrets
  SENTRY_DSN: devcenter-secrets
  STRAPI_URL: devcenter-secrets
  STRAPI_API_TOKEN: devcenter-secrets

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /developer/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

ingress:
  enabled: true
  path: /developer
  hosts: ["devhub-1167-preview.devrel.staging.corp.mongodb.com"]

