service:
  type: ClusterIP
  targetPort: 3000

env:
  HOST_URL: mongodbcom-cdn.website.staging.corp.mongodb.com

envSecrets:
  NPM_EMAIL: devcenter-secrets
  NPM_AUTH: devcenter-secrets
  STRAPI_URL: devcenter-secrets
  DEVHUB_URL: devcenter-secrets

autoscaling:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /developer/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  path: /developer
  hosts: ["mongodbcom-cdn.website.staging.corp.mongodb.com","devcenter-frontend.devrel.staging.corp.mongodb.com"]