// This is just copied from flora because they don't expose it
// Hopefully we can get them to expose it and use it instead.

// https://github.com/10gen/flora/blob/main/src/ThirdPartyLogo/constants.ts#L97

import { EThirdPartyLogoVariant } from '@mdb/flora';
export const LogoPaths: { [key in EThirdPartyLogoVariant]: string } = {
    [EThirdPartyLogoVariant.C]:
        'https://webimages.mongodb.com/_com_assets/cms/ks66s0ohwdti1j4es-lang_c.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.C_PLUS_PLUS]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67kvzgzoi0g33va-lang_c_plus_plus.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.C_SHARP]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67l72x98g3whceo-lang_c_sharp.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GO]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67n6mbb5spon689-lang_go.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVA]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67o2jcxlujkbk0d-lang_java.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVA_RED]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67ofl617k43nfbh-lang_java_red.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVA_LOGOMARK]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67or52h1vtq9spj-lang_java_logomark.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVA_LOGOMARK_RED]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67p0pnlloxd7xqu-lang_java_logomark_red.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVASCRIPT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67pb1b0pxch9df4-lang_javascript.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.JAVASCRIPT_WHITE]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67pjqmlkk6hbrt5-lang_javascript_white.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PERL]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67pv8yhrv81wc52-lang_pearl.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PHP]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67q3q71plcgkyrz-lang_php.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PHP_KNOCKOUT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67qmaunv56pjkcj-lang_php_knockout.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PYTHON]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67qw1a1whct10lb-lang_python.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PYTHON_LOGOMARK]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67r63qo5kuxary0-lang_python_logomark.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PYTHON_LOGOMARK_YELLOW]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67rf0247qeyz7j4-lang_python_logomark_yellow.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PYTHON_STACKED]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67rpgpvz8v3c0fq-lang_python_stacked.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RUBY]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67ry8jk1mga18vz-lang_ruby.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RUBY_KNOCKOUT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67s5ujd11affu87-lang_ruby_knockout.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RUBY_LOGOMARK]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67sdtrn76jurziq-lang_ruby_logomark.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RUBY_LOGOMARK_KNOCKOUT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67sptgens44qpkc-lang_ruby_logomark_knockout.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SCALA]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67swsruf8mrukfd-lang_scala.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SCALA_LOGOMARK_KNOCKOUT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks67t82pir7hv3ptl-lang_scala_logomark_knockout.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.AWS]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6id0fldyolj0yvv-aws.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.AZURE]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6idk2lqjypjk4t7-azure.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.AZURE_OLD]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6idsxqwglzueamt-azure_old.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.CARAHSOFT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ie35g4ikheindg-carahsoft.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.FEATURESPACE]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ieehmj92claby0-featurespace.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GOOGLE_CLOUD]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ientx6nxyanvfn-google_cloud.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GOOGLE_CLOUD_LOGOMARK]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6it6zwfg8u6nrjb-google_cloud_logomark.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RED_HAT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6if5nyi5vs50goc-redhat.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.RED_HAT_KNOCKOUT]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ifdbntwyt0rzu0-redhat_knockout.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.TCS]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ifk6ipbho8ewmu-tos.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ZALONI]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6ifqt4vg57ml6tz-zaloni.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.AICPA_SOC]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6j7f0g0091y4irt-aicpa_soc.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.FEDRAMP]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6ft3y8m0xcur30n-fedramp-logo.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GDPR]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6j85vyqtkx742f3-gdpr.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.HIPAA]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6j8f6cv32h18p0i-hipaa.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ISO_27001]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6j8mjjj50e8zixu-iso_27001.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PCI]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6j8wuk84hx55up8-pci.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SEVEN_ELEVEN]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6es7jbos7hvv09w-7-Eleven.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ACXIOM]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6et2jascmp64ba4-Acxiom.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ACXIOM_WHITE]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6jmq5cufv26sqqc-acxiom_white.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ADOBE_HORIZONTAL_BLACK]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f16wp4j46qcbc1-Adobe-horizontal-black.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ADOBE_HORIZONTAL_RED]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f30ytyvhsl347z-Adobe-horizontal-red.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ADOBE_VERTICAL_BLACK]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f3b9tmt7jckx9b-Adobe-vertical-black.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ADOBE_VERTICAL_RED]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f3mmruyh3xf3fm-Adobe-vertical-red.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ADP]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f6pjpu3c0au7vk-ADP.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.ATD_WHITE]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6jtlv22ewtbxct3-atd_white.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.BARCLAYS]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6f7se6k5ax8fa3g-Barclays.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.BORDERFREE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fbqc6kbb4nkpw0-Borderfree.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.BOSH]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fc1009fao1f6in-Bosch.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.COINBASE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fcd51mwis3uv4z-Coinbase.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.COMPARE_THE_MARKET]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fcnjuo9t5h25x0-Compare%20the%20Market.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.EA]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fsegcpeuyw49aq-EA.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.EBAY]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fsnogsj8arp6vp-Ebay.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.EHARMONY]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fsweujn9sso6wi-eharmony.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.FORBES]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fuwe4n1ptbykc6-Forbes.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GOOGLE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fv7u35e8f7ksql-Google.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GOOGLE_ICON]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fvgdym4qzsgqo3-Google%20Icon.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.GOV_UK]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fvvdfx5091481o-gov.uk.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.HUMANITIX]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6kmbqzdycm59idh-humanitix.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.HUMANITIX_lOGOMARK]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6lsq1xj1l3gyghw-humanitix_logomark.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.INGENIQ]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fyk1whj88z80b5-Ingeniq.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.INTUIT]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fyvdyxnbb7hk6c-Intuit.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.INVISION]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6fz6q2gf69z4nzh-Invision.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.KPMG]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g1yj0qxcuh9g10-KPMG.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.LIBERTY_MUTUAL]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g28v57p1j6yss9-LibertyMutual.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.MET_OFFICE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g2yh5102dl9znd-Met%20Office.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.OXFORD_NANOPORE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g4smemfi3ed2t8-Oxford%20Nanopore.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.NESTO]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6lxdqpo7morksyp-nesto.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PATHAO]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6m2l4wtu84ffv4b-pathao.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PITNEY_BOWES]:
        'https://webimages.mongodb.com/_com_assets/cms/ks6m2xrynwanj8ph6-pitney_bowes.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.PRACTICEFUSION]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g5cq2jtx1cuy3v-Practicefusion.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SANOMA]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g7mzgvgqpqm0ds-Sanoma.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SAP]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g7xek6crjapgl3-SAP.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SEGA]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g9cgdb0oyojhzh-Sega.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SOFTWARE_AG]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6g9yihl2d2rn9xz-software%20AG.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SQUARE_SPACE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gaa2dcm92ty4vt-Squarespace.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SQUARE_SPACE_STACKED]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gbvoyn2b51i55q-Squarespace-Stacked.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.SWIMLANE]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gc7jnqhscclq45-Swimlane.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.TOYOTA_MH1]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gcggixl0qp659i-ToyotaMH1.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.TOYOTA_MH2]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gcpxvmgfg2bat3-ToyotaMH2.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.VERIZON]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gez4jikdzp1e0m-verizon.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.VSCO]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6gg6ueye3a9ldmy-VSCO.svg?auto=format%252Ccompress',
    [EThirdPartyLogoVariant.YOU_GOV]:
        'https://webimages.mongodb.com/_com_assets/cms/kr6ggflr1lky2rudf-YouGov.svg?auto=format%252Ccompress',
};
