export const productToLogo: { [key: string]: string } = {
    Atlas: 'atlas_product_family',
    MongoDB: 'mdb_database',
    'Realm (Mobile)': 'realm_product_family',
    Compass: 'mdb_compass',
    'Cloud Manager': 'atlas_cloud_manager',
    'Ops Manager': 'mdb_ops_manager',
    SQL: 'connectors_sql_connector',
    'Multi-Cloud': 'cloud_multicloud',
    'Data API': 'atlas_dataapi',
    Monitoring: 'general_features_realtime',
    'Online Archive': 'atlas_online_archive',
    'Full Text Search': 'atlas_full_text_search',
    Charts: 'atlas_charts',
    Triggers: 'atlas_triggers',
    'Data Lake': 'atlas_data_lake',
    API: 'general_features_api',
    'Data Modeling': 'mdb_document_model',
    'Change Streams': 'mdb_change_streams',
    'Aggregation Framework': 'mdb_aggregation_pipelines',
    CRUD: 'mdb_document_model',
    Transactions: 'general_features_transactions',
    'Time Series': 'mdb_time_series',
    Security: 'general_security',
    'Data Visualization': 'general_features_data_analytics',
    Shell: 'mdb_shell',
    SDK: 'realm_sdk',
    'Realm Sync': 'realm_sync',
};
