name: Integration Tests
on:
    pull_request:
        branches: [main]
env:
    NPM_AUTH: ${{ secrets.ARTIFACTORY_NPM_AUTH }}
    NPM_EMAIL: ${{ secrets.ARTIFACTORY_NPM_EMAIL }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
jobs:
    amplify-test-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout target branch
              uses: actions/checkout@v2
            - name: Use Node 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: set amplify env name
              id: setenvname
              run: |
                  # use GITHUB_HEAD_REF that is set to PR source branch
                  # also remove -_ from branch name and limit length to 10 for amplify env restriction
                  echo "##[set-output name=amplifyenvname;]$(echo ${GITHUB_HEAD_REF//[-_]/} | cut -c-10)"
            - name: deploy test environment
              uses: ambientlight/amplify-cli-action@0.3.0
              with:
                  amplify_command: add_env
                  amplify_env: ${{ steps.setenvname.outputs.amplifyenvname }}
                  amplify_cli_version: '3.17.1-alpha.35'
            - name: Cache node modules
              uses: actions/cache@v2
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: Install Cypress
              if: steps.cache.outputs.cache-hit == 'true'
              run: ./node_modules/.bin/cypress install
            - name: Build
              run: yarn build
            - name: Run Cypress
              uses: cypress-io/github-action@v2
              with:
                  install: false
                  start: yarn start
                  wait-on: 'http://localhost:3000'
            - name: Generate artifacts on failure
              uses: actions/upload-artifact@v2
              if: ${{ failure() }}
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - name: undeploy test environment
              uses: ambientlight/amplify-cli-action@0.3.0
              # run even if previous step fails
              if: failure() || success()
              with:
                  amplify_command: delete_env
                  amplify_env: ${{ steps.setenvname.outputs.amplifyenvname }}
                  amplify_cli_version: '3.17.1-alpha.35'
                  delete_lock: false
