name: Pull Request Checks
on:
    pull_request:
        branches: [main]
jobs:
    check-formatting-and-lint:
        runs-on: ubuntu-latest
        env:
            NPM_AUTH: ${{ secrets.ARTIFACTORY_NPM_AUTH }}
            NPM_EMAIL: ${{ secrets.ARTIFACTORY_NPM_EMAIL }}
        steps:
            - name: Checkout target branch
              uses: actions/checkout@v2
            - name: Use Node 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Cache node modules
              uses: actions/cache@v2
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: Run Prettier
              run: yarn format:check
            - name: Lint
              run: yarn lint
